# Generated by Django 6.0.4 on 2026-04-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0002_room_is_private_room_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='room_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_private', 'created_at'], name='room_app_ro_is_priv_38f135_idx'),
        ),
    ]
